version: "3.8"

services:
  mongo_db:
    image: mongo:jammy
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=johndoe
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  sisyphus-api:
    container_name: sisyphus-api
    image: sisyphus/sisyphus:1.0.3
    ports:
      - '8080:8080'
    depends_on:
      - mongo_db
  sisyphus-frontend:
    container_name: sisyphus-frontend
    image: sisyphus/sisyphus-frontend:1.0.2
    ports:
      - '9090:80'
    depends_on:
      - sisyphus-api
volumes:
  db: