version: "3.8"

services:
  mongo_db:
    image: mongo:jammy
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=johndoe
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  sisyphus-api:
    container_name: sisyphus-api
    image: dev/sisyphus-api:1.0.4
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        APP_VERSION: 1.1.4
        SCRAPE: http://sisyphus-scraper:5858/scrape
    ports:
      - '8080:8080'
    depends_on:
      - mongo_db
  sisyphus-frontend:
    container_name: sisyphus-ui
    image: dev/sisyphus-ui:1.0.3
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '9090:80'
    depends_on:
      - sisyphus-api
  sisyphus-scraper:
    container_name: sisyphus-scraper
    image: dev/sisyphus-scraper:1.0.0
    build:
      context: python
      dockerfile: Dockerfile
    ports:
      - '5858:5858'
volumes:
  db: