image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  PROFILE: ci/cd

stages:
  - compile

before_script:
  - export APP_VERSION=$(./mvnw help:evaluate -Dexpression="project.version" -q -DforceStdout)

compile:
  stage: compile
  script:
    - cd backend
    - ./mvnw clean compile
  only:
    changes:
      - backend/**
      - docker-compose.yml
    refs:
      - ci/cd

# test