spring:
  data:
    mongodb:
      uri: mongodb://mateuszuran:local123@localhost:28018/sisyphus-db?authSource=admin
application:
  cors:
    origins: http://localhost:4200, http://localhost:9090

server:
  port: 8088

  servlet:
    context-path: /api/v1/