spring:
  data:
    mongodb:
      uri: mongodb://johndoe:password@mongo_db:27017/sisyphus-db?authSource=admin
application:
  cors:
    origins: http://localhost:9090

server:
  port: 8080

  servlet:
    context-path: /api/v1/

scraper:
  api: http://127.0.0.1:5858/scrape