name: Python Scraper API Pipeline

on:
  push:
    branches:
      - ci/cd
      - master
    paths:
      - python/**  # Adjust this if needed
      - 'Dockerfile'
      - .github/workflows/*-scraper.yml

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    name: Install dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd python
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  lint:
    runs-on: ubuntu-latest
    name: Lint code
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install linting tools
        run: |
          cd python
          pip install flake8

      - name: Run linting
        run: |
          cd python
          flake8 .

  build-image:
    runs-on: ubuntu-latest
    name: Build Docker image
    needs: [install-dependencies, lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract project version
        id: extract_version
        run: |
          cd python
          echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to dockerhub
        uses: docker/build-push-action/@v5
        with:
          context: python
          file: python/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sisyphus-scraper:${{ steps.extract_version.outputs.VERSION }},${{ secrets.DOCKERHUB_USERNAME }}/sisyphus-scraper:latest
          build-args: |
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}